---
title: "TrendsPO presentation OBIS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(robis)
library(obistools)
library(dplyr)
library(leaflet)
library(ggplot2)
library(maps)
library(dplyr)
library(worrms)
library(mregions)

plot_all <- function(data) {
  ggplot() +
    geom_polygon(data = world, aes(x = long, y = lat, group = group), fill = "#dddddd") +
    geom_point(data = data, aes(x = decimalLongitude, y = decimalLatitude))
}

plot_qc <- function(data, qc, baseplot=NULL) {
  data$qcnum <- as.factor(qcflags(data$qc, qc))
  ggplot() +
    geom_polygon(data = world, aes(x = long, y = lat, group = group), fill = "#dddddd") +
    geom_point(data = data, aes(x = decimalLongitude, y = decimalLatitude, color = qcnum))
}

check_worms_distribution <- function(aphiaid) {
  worms_distribution <- worrms::wm_distribution(aphiaid)

  ok <- rep(FALSE, nrow(calfin))
  for (url in worms_distribution$locationID) {
    mr <- httr::content(httr::GET(url))
    
    # naive version
    extent <- c(mr$minLongitude, mr$maxLongitude, mr$minLatitude, mr$maxLatitude)
    if(length(extent) == 4 &&!any(is.na(extent))) {
      ok <- ok | ((mr$minLongitude <= calfin$decimalLongitude) & (calfin$decimalLongitude <= mr$maxLongitude) & (mr$minLatitude <= calfin$decimalLatitude) & (calfin$decimalLatitude <= mr$maxLatitude))
    }

    # EXPANDED VERSION USING WMS/WFS
    # wms <-  httr::content(httr::GET(paste0("http://www.marineregions.org/rest/getGazetteerWMSes.json/", mr$accepted, "/")))
    # if(length(wms) > 0) {
    #   print(paste(mr$accepted, wms[[1]]))
    # }

  }
  ok
}
```

Load the data

```{r, cache=TRUE}
world <- map_data("world")
calfin <- occurrence("Calanus finmarchicus")
xy <- lookup_xy(calfin, shoredistance = FALSE, grids = TRUE, areas = FALSE)
```

Plot number of records per year

```{r}
calfin_yearcount <- calfin %>% count(yearcollected)
ggplot(calfin_yearcount, aes(x=yearcollected, y=n)) +
  geom_point()
```

Plot environmental data

```{r}
# salinity - temperature
ggplot(xy[complete.cases(xy),], aes(x=sssalinity, y=sstemperature)) +
  geom_point()
```

Plot on map based on qc flag 27

```{r}
plot_qc(calfin, qc=27) # spatial outliers
```

Plot on map based on the distribution in WoRMS  

**_WARNING_ The function for the WoRMS distribution is not finished.**  
[See WoRMS for the distribution](http://marinespecies.org/aphia.php?p=taxdetails&id=104464#distributions)

```{r}
ok <- check_worms_distribution(calfin$aphiaID[1])
calfin_ok <- calfin[ok, ]
xy_ok <- xy[ok, ]

plot_all(calfin_ok)
```

