---
title: "OBIS Indonesia R demo"
output: html_document
editor_options: 
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width = 8, fig.height = 4) 
```

```{r}
library(robis)
library(ggplot2)
library(dplyr)
library(rnaturalearth)
library(ggthemes)
library(sf)
library(RColorBrewer)
library(leaflet)
source("lib.R")

occ <- occurrence(areaid = 115)

stations <- occ %>%
  group_by(decimalLongitude, decimalLatitude) %>%
  summarize(records = n())

world <- ne_countries(country = "indonesia", scale = "large", returnclass = "sf")

ggplot() +
  geom_sf(data = world, fill = "#000000", color = "#000000") +
  geom_point(data = stations, aes(x = decimalLongitude, y = decimalLatitude), size = 0.5, color = "#cc3300") +
  coord_sf() + ggtitle("OBIS occurrence records in Indonesia") + theme_map
```

```{r}
animalia <- occ %>% filter(kingdom == "Animalia" & !is.na(phylum) & !is.na(date_year))
colors <- colorRampPalette(brewer.pal(11, "RdBu"))(length(unique(animalia$phylum)))

ggplot(animalia) +
  geom_histogram(aes(x = date_year, fill = phylum), binwidth = 2) + theme_bars + scale_fill_manual(values = colors)
```

```{r}
bivalvia <- occ %>%
  filter(class == "Bivalvia")

xy <- lookup_xy(bivalvia, shoredistance = TRUE, grids = TRUE, areas = FALSE)
bivalvia <- bind_cols(bivalvia, xy)

leaflet(bivalvia) %>%
  addProviderTiles("Esri.OceanBasemap") %>%
  addCircleMarkers(
    popup = ~scientificName,
    ~decimalLongitude, ~decimalLatitude, weight = 1, opacity = 1, fillOpacity = 0.2, stroke = FALSE,
    color = ~ifelse(!is.na(bathymetry) & bathymetry > 100, "navy", "tomato"),
    radius = ~ifelse(!is.na(bathymetry) & bathymetry > 100, 6, 4)
  )
```





